### ISSUE TITLE
Automatically Download the file from cambridge server. 

### ISSUE THREAD

**Issue by prajwal309** [disruptiveplanets/splash#8]
Cambridge pipeline has finished running SPECULOOS data. Need to streamline downloading automatize downloading the data and running the data.

**Comment by ppp-one** [comment]
Portal_v2 is nearly done in that regard. Can you specifically tell me what you need?  Nightly data is easy to get, global data requires Catriona to guide me.

**Comment by prajwal309** [comment]
It would be ideal to download both the fits file as well as the differential light curves. I believe I already have the function for the differential light curve, but if you have a function for fits file that would be great.

**Comment by ppp-one** [comment]
I'll send you some stuff on the Slack for this.

**Comment by prajwal309** [comment]
Added functionality to download the data from Cambridge server using the Php function provided by Peter. Thanks a lot Peter.
